services:
  - type: web
    name: quizzard-backend
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5005
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false